### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by pbertoni89** [GPMueller/mwe-cpp-exception#1]
$ mkdir build; cd build; cmake ..; make

> In file included from src/API.cpp:3:0:
include/detail/Exception.hpp:12:9: error: expected class-name before ‘{’ token

    $ gcc -v
    gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)

**Comment by GPMueller** [comment]
An `#include <stdexcept>` was missing, but this has now been added with commit f66496c57d76afbc8da4abd8c1e4df1ed38d7428.
